---
name: Test

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9, 3.6, 3.7, 3.8, '3.10']
        include:
          - os: macos-latest
            python-version: 3.9
          - os: windows-latest
            python-version: 3.9

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install wheel
      - run: pip install -e .[test]

      - run: pytest
